services:
  bot:
    image: srb-bot
    container_name: srb-bot
    build: ./services/bot
    env_file:
      - .env
    depends_on:
      - mongo

  daemon:
    image: srb-daemon
    container_name: srb-daemon
    build: ./services/daemon
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: srb-mongo
    command:
      - '--logpath'
      - '/dev/null'
    volumes:
      - ./services/mongo/data:/data/db

