services:
  bot:
    image: srb-bot
    container_name: srb-bot
    env_file:
      - .env
    depends_on:
      - mongo

  daemon:
    image: srb-daemon
    container_name: srb-daemon
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: srb-mongo
    # ports:
    #  - 2717:27017
    volumes:
      - ./services/mongo/data:/data/db

